[main]
font=Noto Sans:size=12
terminal=xfce4-terminal
prompt="❯ "
icon-theme=Papirus
show-icons=yes
lines=12
width=45
horizontal-pad=20
vertical-pad=10
inner-pad=5

# Colores Gruvbox Dark
[colors]
background=282828ff
text=ebdbb2ff
match=fb4934ff
selection=3c3836ff
selection-text=ebdbb2ff
selection-match=fb4934ff
border=458588ff

[border]
width=1
radius=0
